name: NotionGraph
options:
  bundleIdPrefix: com.notiongraph
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"

targets:
  NotionGraph-iOS:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - NotionGraph/Sources
    resources:
      - NotionGraph/Assets.xcassets
    info:
      path: NotionGraph/Info.plist
      properties:
        CFBundleName: NotionGraph
        CFBundleDisplayName: NotionGraph
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.notiongraph.ios
        PRODUCT_NAME: NotionGraph
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        ENABLE_PREVIEWS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic

  NotionGraph-macOS:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - NotionGraph/Sources
    resources:
      - NotionGraph/Assets.xcassets
    info:
      path: NotionGraph/Info.plist
      properties:
        CFBundleName: NotionGraph
        CFBundleDisplayName: NotionGraph
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        LSMinimumSystemVersion: "14.0"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.notiongraph.macos
        PRODUCT_NAME: NotionGraph
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        ENABLE_PREVIEWS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "-"
        ENABLE_HARDENED_RUNTIME: YES

schemes:
  NotionGraph-iOS:
    build:
      targets:
        NotionGraph-iOS: all
    run:
      config: Debug
    archive:
      config: Release

  NotionGraph-macOS:
    build:
      targets:
        NotionGraph-macOS: all
    run:
      config: Debug
    archive:
      config: Release
